# Generated by Django 4.2.4 on 2023-08-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('item_type', models.CharField(choices=[('M', 'M'), ('S', 'S')], max_length=1)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_path', models.CharField(max_length=160)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_id', to='App.item')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_id', to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('condition', models.CharField(choices=[('U', 'U'), ('N', 'N')], max_length=1)),
                ('avg_price', models.FloatField()),
                ('total_quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField()),
                ('date_sold', models.DateField()),
                ('bought_for', models.FloatField()),
                ('sold_for', models.FloatField()),
                ('notes', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('U', 'U'), ('N', 'N')], max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
