# Generated by Django 4.2.4 on 2023-09-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bought_for',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sold_for',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
