# Generated by Django 4.2.4 on 2023-09-08 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_portfolio_date_bought_alter_portfolio_bought_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
